version: "3.8"

services:
  elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch-1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.system_call_filter=false
      - node.name=docker-1
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    networks:
     - elastic-network

networks:
  elastic-network:
    name: elastic-network
    driver: bridge