@baseUrlProduct = http://localhost:9200/products
@baseUrlCustomer = http://localhost:9200/customers
@baseUrlOrder = http://localhost:9200/orders

@baseUrl = http://localhost:9200

### create index customers
PUT http://localhost:9200/customers

### create index products
PUT http://localhost:9200/products

### create index orders
PUT http://localhost:9200/orders

### delete index customers
DELETE http://localhost:9200/customers

### delete index products
DELETE http://localhost:9200/products

### delete index orders
DELETE http://localhost:9200/orders

### show all indices
GET http://localhost:9200/_cat/indices

### update dynamic mapping customers
PUT http://localhost:9200/customers/_mapping
Content-Type: application/json

{
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}

### update dynamic mapping customers numeric detection
PUT http://localhost:9200/customers/_mapping
Content-Type: application/json

{
    "numeric_detection": true
   
}

### get dynamic mapping customers
GET http://localhost:9200/customers/_mapping

### update dynamic mapping orders
PUT http://localhost:9200/orders/_mapping
Content-Type: application/json

{
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}

### update dynamic mapping orders numeric detection
PUT http://localhost:9200/orders/_mapping
Content-Type: application/json

{
    "numeric_detection": true
   
}

### get dynamic mapping orders
GET http://localhost:9200/orders/_mapping

### update dynamic mapping products
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}

### update  dynamic mapping products numeric detection
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
    "numeric_detection":true
}

### get dynamic mapping products
GET http://localhost:9200/products/_mapping

### insert customers wildan
POST http://localhost:9200/customers/_create/wildan
Content-Type: application/json

{
    "name": "Akhmad Wildan",
    "register_at": "2023-01-01 00:00:00"
}


### insert products 1
POST http://localhost:9200/products/_create/1
Content-Type: application/json

{
    "name": "Indomie Ayam Bawang",
    "price": "2000"
}

### insert products 2
POST http://localhost:9200/products/_create/2
Content-Type: application/json

{
    "name": "Mie Sedap Soto",
    "price": "2000"
}

### insert orders 1
POST http://localhost:9200/orders/_create/1
Content-Type: application/json

{
    "corder_date": "2024-05-02 00:00:00",
    "customer_id": "wildan",
    "total": "8000", 
    "items": [
        {
            "product_id": "1",
            "price": "2000",
            "quantity": "2"
        },
        {
            "product_id": "2",
            "price": "2000",
            "quantity": "2"
        }
    ]
}

### GET Customers Wildan
GET  http://localhost:9200/customers/_doc/wildan

### GET Source Customers Wildan
GET  http://localhost:9200/customers/_source/wildan

### Check Customers Wildan
HEAD  http://localhost:9200/customers/_doc/wildan

### Check Customers Salah
HEAD  http://localhost:9200/customers/_doc/salah

### Multiget products
POST http://localhost:9200/products/_mget
Content-Type: application/json

{
    "ids": [
        "1", 
        "2"
    ]
}

### Search products
POST http://localhost:9200/products/_search

### Search products page 1
POST http://localhost:9200/products/_search?size=1&from=0

### Search products page 2
POST http://localhost:9200/products/_search?size=1&from=1

### Search products sort by price
POST http://localhost:9200/products/_search?sort=price:desc

### Search products sort by name : tidak bisa karena type datanya text
POST http://localhost:9200/products/_search?sort=name:asc

### Search products sort by price, name
POST http://localhost:9200/products/_search?sort=price:desc,name:desc


### Save products 3
POST http://localhost:9200/products/_doc/3
Content-Type: application/json

{
     "name": "Pop Mie Rasa Bakso",
    "price": 2500
}

### Save products 4

POST http://localhost:9200/products/_doc/4
Content-Type: application/json

{
     "name": "Samsung Galaxy S9+",
    "price": 20000000
}

### Save products 5
POST http://localhost:9200/products/_doc/5
Content-Type: application/json

{
    "name": "Acer Prodator XXI",
    "price": 250000000
}

### Update products 5
POST http://localhost:9200/products/_update/5
Content-Type:  application/json

{
    "doc": {
        "price": 300000000
    }
}

### Insert customers spammer
POST {{baseUrlCustomer}}/_create/spammer
Content-Type: application/json

{
    "name": "Spammer",
    "register_at": "2024-05-03 00:00:00"
}

### Delete customers spammer
DELETE {{baseUrlCustomer}}/_doc/spammer


### bulk api
POST {{baseUrl}}/_bulk 
Content-Type: application/json

< bulk.json 

### create alias customer and order
POST {{baseUrl}}/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "add": {
                 "alias": "customer",
                "index": "customers"
            }
           
        },
        {
             "add": {
                 "alias": "order",
            "index": "orders"
             }
           
        }
    ]
}

### get alias
GET {{baseUrl}}/_aliases

### Search customer
POST http://localhost:9200/customer/_search

### Search order
POST http://localhost:9200/order/_search


### BATAS sabtu 04-05-2024 #####

### Create index orders_v2
PUT {{baseUrl}}/orders_v2

### Update mapping index orders_v2
PUT {{baseUrl}}/orders_v2/_mapping
Content-Type: application/json

{
  "numeric_detection": true,
  "date_detection": true,
  "dynamic_date_formats": [
     "yyyy-MM-dd HH:mm:ss",
      "yyyy-MM-dd",
      "yyyy/MM/dd HH:mm:ss",
      "yyyy/MM/dd"
  ]
 
}

### Reindex orders data
POST {{baseUrl}}/_reindex
Content-Type: application/json

{
  "source": {
    "index": "orders"
  },
  "dest": {
    "index": "orders_v2"
  }
}

### Remove order alias: orders and add order alias: orders_v2
POST {{baseUrl}}/_aliases
Content-Type: application/json

{
  "actions": [
    {
      "remove": {
        "index": "orders",
        "alias": "order"
      }
    },
    {
      "add": {
        "index": "orders_v2",
        "alias": "order"
      }
    }
  ]
}


### search alias order 
POST {{baseUrl}}/order/_search


### search order includes total, customer_id, items.product_id
POST {{baseUrl}}/order/_search?_source_includes=total,customer_id,items.product_id

### search products exclude pice
POST {{baseUrl}}/products/_search?_source_excludes=price

### get order
GET {{baseUrl}}/order/_doc/1?_source_includes=total,customer_id


### Create index customers_v2
PUT {{baseUrl}}/customers_v2

### Update mapping customers_v2
PUT {{baseUrl}}/customers_v2/_mapping
Content-Type: application/json

{
    "numeric_detection": true,
    "date_detection": true,
    "dynamic_date_formats": [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ],
    "properties": {
        "username": {
            "type": "keyword"
        },
        "first_name": {
            "type": "text"
        },
        "last_name": {
            "type": "text"
        },
        "email": {
            "type": "keyword"
        },
        "gender": {
            "type": "keyword"
        },
        "birth_date": {
            "type": "date",
            "format": "yyyy-MM-dd"
        }
    }
},

### add alias customer for customers_v2 and remove for custmers
POST {{baseUrl}}/_aliases
Content-Type: application/json

{
    "actions": [
        {
            "remove": {
                "index": "customers",
                "alias": "customer"
            }
        },
        {
            "add": {
                "index": "customers_v2",
                "alias": "customer"
            }
        }
    ]
}

### get all alias  
GET {{baseUrl}}/_aliases

### bulk insert customer
POST {{baseUrl}}/_bulk
Content-Type: application/json

< customers.json

### search customer
POST {{baseUrl}}/customer/_search

